#!/usr/bin/env python2.7

import cffi

ffi = cffi.FFI()

ffi.cdef("""
int crypto_stream_xor(
        unsigned char *out,
        const unsigned char *in,
        unsigned long long inlen,
        const unsigned char *n,
        const unsigned char *k
);
""")

#ffi.cdef("""
#       void *memset(void *s, int c, size_t n);
#""")


blib = ffi.dlopen("target/lib/libbletchleyprimitives.so.1")
key = ffi.new("unsigned char[]", 32)
nonce = ffi.new("unsigned char[]", 8)
toencrypt = ffi.new("unsigned char[]", 50)
output = ffi.new("unsigned char[]", 50)
print output
blib.crypto_stream_xor(output, toencrypt, 50, nonce, key)
