#!/usr/bin/env python2.7

import cffi

ffi = cffi.FFI()

ffi.cdef("""
extern int crypto_core(
        unsigned char *out,
  const unsigned char *in,
  const unsigned char *k,
  const unsigned char *c
);
""")

#ffi.cdef("""
#       void *memset(void *s, int c, size_t n);
#""")


blib = ffi.dlopen("target/lib/libbletchleyprimitives.so.1")
key = ffi.new("unsigned char[]", [0x80] + 31*[0])
inpt = ffi.new("unsigned char[]", 32*[0])
sigma = ffi.new("unsigned char[]", "expand 32-byte k")
output = ffi.new("unsigned char[]", 64)
blib.crypto_core(output, inpt, key, sigma);
print " ".join(["%02x" % b for b in output])
