#!/usr/bin/env python2.7

import cffi

ffi = cffi.FFI()

with open("target/lib/cffi_headers/bletchley/primitives/cffi_crypto_core_salsa20.h") as f:
    ffi.cdef(f.read())

blib = ffi.dlopen("target/lib/libbletchleyprimitives.so.1")
print blib.cffi_crypto_core_salsa20_OUTPUTBYTES
print ffi.string(blib.cffi_crypto_core_salsa20_IMPLEMENTATION)
print ffi.string(blib.cffi_crypto_core_salsa20_VERSION)
key = ffi.new("unsigned char[]", [0x80] + 31*[0])
inpt = ffi.new("unsigned char[]", 32*[0])
sigma = ffi.new("unsigned char[]", "expand 32-byte k")
output = ffi.new("unsigned char[]", 64)
blib.crypto_core_salsa20(output, inpt, key, sigma);
print " ".join(["%02x" % b for b in output])
